/**
 * Migration runner — applies every not-yet-applied SQL file in
 * `database/migrations/` (generated by `npm run db:generate`, i.e.
 * `drizzle-kit generate`) to `DATABASE_URL`, tracking what's already been
 * applied in Drizzle's own `__drizzle_migrations` bookkeeping table.
 *
 * Deliberately a plain script, not an API route or admin panel button:
 * schema migrations are a deploy-time operation
 * (10-backend-architecture.md Section 4.1's separation of `database/` from
 * application code), run via CI/CD or by an operator, never by application
 * runtime code.
 */
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import dotenv from "dotenv";

dotenv.config({ path: ".env" });

if (!process.env.DATABASE_URL) {
  dotenv.config();
}

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error('DATABASE_URL is required to run migrations.');

  const migrationClient = postgres(databaseUrl, { max: 1, prepare: false });
  const db = drizzle(migrationClient);

  console.log('Applying migrations from ../database/migrations ...');
  await migrate(db, { migrationsFolder: '../database/migrations' });
  console.log('Migrations applied successfully.');

  await migrationClient.end();
}

main().catch((error) => {
  console.error('Migration failed:', error);
  process.exit(1);
});
